#!/usr/bin/env python3
"""Port a scaffolded harness to Cursor or Codex.

The harness is generated for Claude Code. Cursor and Codex have their own rule and hook systems, and
both are close enough to Claude Code's that the harness ports rather than being rewritten. This script
reads a repo that has already been scaffolded (it has .claude/rules/ and .claude/hooks/) and emits the
tool-specific files next to it.

    python port.py --target <repo> --tool codex
    python port.py --target <repo> --tool cursor
    python port.py --target <repo> --tool all
    python port.py --target <repo> --tool all --force   # overwrite the files that differ
    python port.py --self-test          # run the adapter against documented sample payloads

NOTHING IS OVERWRITTEN
----------------------
Same contract as the scaffolder, for the same reason: a ported file is a file a human may have
edited afterwards. Every emitted file is reported as ADDED (did not exist), KEPT (exists and is
byte-identical, so it is not rewritten) or CONFLICT (exists and differs - NOT written). --force
turns a CONFLICT into FORCED and overwrites it, and is the only way this script touches content it
did not write. A run with any CONFLICT exits non-zero, because the failure being fixed here is the
silent one: the porter used to call write_text() unconditionally, so re-porting a repo threw away
hand-tuned .mdc rules and hand-registered hooks and still printed a clean report.

Everything emitted carries "generated by port.py" - a comment line in each .mdc, a "_generated_by"
key in each hooks.json - so a later pass, or a human reading a diff, can tell this script's output
from their own without having to re-derive it.

WHAT PORTS, AND WHAT DOES NOT
-----------------------------
Rules port in full. Enforcement ports with two caveats, both honest and documented in the output:

  Codex   PreToolUse hooks are structurally identical to Claude Code's: same {cwd, tool_name,
          tool_input.command} input, same exit-2-to-deny, same hooks.json shape. The Bash-checking
          hooks (guard-main-commit, check-commit-msg, protect-secrets) run unchanged. Codex routes
          file edits through apply_patch with the path inside tool_input.command, not a tool_input.
          file_path, so protect-adr (which reads file_path) is best-effort on Codex.

  Cursor  Events and output differ (beforeShellExecution / beforeReadFile, JSON {"permission":...}),
          so a small adapter normalises Cursor's payload to the shape the existing hooks expect and
          translates their exit code back. afterFileEdit is observational-only in Cursor, so an edit
          to an Accepted ADR cannot be blocked before it happens there - only flagged after.

  Both    guard-agent-spawn does not port at all: neither Cursor nor Codex exposes a subagent-spawn
          hook point, because neither has Claude Code's Agent tool. The spawn boundary is a
          Claude-Code-only control; in the other tools the roster exists as rules text, not as an
          enforced gate. This is recorded in the generated output so nobody assumes otherwise.

This wiring is built to each tool's published hook schema. It is unit-tested here against documented
sample payloads, but run one real action in the tool to smoke-test it in your environment.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import pathlib
import re
import shutil
import subprocess
import sys

# --------------------------------------------------------------------------- the write contract

# Stamped into every file this script emits so a later pass can tell the porter's own output from a
# human's. One string for all three formats, so `grep -r "generated by port.py"` answers "what did
# this script write?" exactly. Deliberately carries no timestamp and no version: either would make
# every re-port differ from its own previous output, so every file would report CONFLICT and the
# marker would defeat the contract it exists to support.
GENERATED_BY = "generated by port.py"


def emit(path: pathlib.Path, body: str, force: bool = False) -> str:
    """Write `body` to `path` under the scaffolder's contract, and report what happened to it.

        ADDED     did not exist, written
        KEPT      exists and is byte-identical to what we would write, left alone
        CONFLICT  exists and differs - NOT written
        FORCED    exists, differs, and --force was passed, so it was overwritten

    A ported file is a file a human may have edited afterwards. Every emitter here used to call
    write_text() unconditionally, so a second port discarded those edits without a word.

    Bytes, not text: write_text() translates "\\n" to "\\r\\n" on Windows, so a file written through
    it never compares equal to the payload it was written from. That would report CONFLICT on every
    re-port of this script's own output, which is worse than useless - it trains people to --force.
    """
    payload = body.encode("utf-8")
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if path.read_bytes() == payload:
            return "KEPT"
        if not force:
            return "CONFLICT"
        path.write_bytes(payload)
        return "FORCED"
    path.write_bytes(payload)
    return "ADDED"


# --------------------------------------------------------------------------- rules: Claude -> Cursor

FRONTMATTER = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def parse_paths(frontmatter: str) -> list[str]:
    """Pull the `paths:` YAML list out of a rule's frontmatter. Minimal parser - the harness only
    ever emits a flat list of quoted globs, so a full YAML dependency is not warranted."""
    globs: list[str] = []
    in_paths = False
    for line in frontmatter.splitlines():
        if re.match(r"^paths:\s*$", line):
            in_paths = True
            continue
        if in_paths:
            m = re.match(r"^\s*-\s*(.+?)\s*$", line)
            if m:
                globs.append(m.group(1).strip().strip('"').strip("'"))
            elif line.strip() and not line.startswith((" ", "\t")):
                break
    return globs


def to_cursor_rule(text: str, source: str = "") -> str:
    """Convert one .claude rule to a .cursor/rules .mdc.

    no `paths:`  -> alwaysApply: true   (Cursor loads it every turn)
    `paths: [g]` -> globs: g,g          (Cursor auto-attaches on a matching file)
    """
    m = FRONTMATTER.match(text)
    fm, body = (m.group(1), text[m.end():]) if m else ("", text)
    desc = ""
    dm = re.search(r"^description:\s*(.+)$", fm, re.MULTILINE)
    if dm:
        desc = dm.group(1).strip()

    globs = parse_paths(fm)
    out = ["---"]
    if desc:
        out.append(f"description: {desc}")
    if globs:
        out.append(f"globs: {','.join(globs)}")
    else:
        out.append("alwaysApply: true")
    out.append("---")
    out.append("")
    # The provenance marker goes BELOW the closing ---, as an HTML comment in the markdown body.
    # Cursor parses the frontmatter as YAML, so an unkeyed comment line inside it is a parse error
    # and a rule that fails to parse is a rule that never loads; in the body it renders as nothing.
    origin = f" from {source}" if source else ""
    out.append(f"<!-- {GENERATED_BY}{origin}. Hand edits are reported as CONFLICT and left alone;"
               " re-run port.py to regenerate. -->")
    out.append("")
    out.append("")
    return "\n".join(out) + body.lstrip("\n")


def port_cursor_rules(claude_rules: pathlib.Path, dest: pathlib.Path,
                      force: bool = False) -> list[tuple[str, pathlib.Path]]:
    written: list[tuple[str, pathlib.Path]] = []
    dest.mkdir(parents=True, exist_ok=True)
    for p in sorted(claude_rules.glob("*.md")):
        out = dest / (p.stem + ".mdc")
        body = to_cursor_rule(p.read_text(encoding="utf-8"), f".claude/rules/{p.name}")
        written.append((emit(out, body, force), out))
    return written


# --------------------------------------------------------------------------- hooks

# Adapter checks the self-test runs per hook flavor, asserted against the real count at the end of
# self_test_flavor() and read by scripts/check_numbers.py to police the published figure. Only
# meaningful on a full run: a machine with no interpreter for a flavor skips the behaviour half.
# 7 write-contract checks (self_test_contract) + 3 adapter wiring checks + 6 adapter behaviour cases.
CHECKS_PER_FLAVOR = 16

# The Bash-matching hooks that need no per-payload adaptation on Codex.
BASH_HOOKS = ["guard-main-commit", "check-commit-msg", "protect-secrets"]
# Hooks that inspect a file path.
FILE_HOOKS = ["protect-adr", "protect-secrets"]

CURSOR_ADAPTER = r'''#!/usr/bin/env python3
# Cursor hook adapter (generated by port.py). Normalises Cursor's hook payload to the shape the
# harness's .claude/hooks/*.sh expect, runs the relevant hooks, and translates their exit code into
# Cursor's {"permission": ...} output. Do not edit by hand; re-run port.py to regenerate.
import json, shutil, subprocess, sys, pathlib

# Filled in by port.py from the harness that was actually scaffolded. A windows harness ships
# only .ps1 hooks, and an adapter that looked for .sh found nothing, skipped every hook, and
# returned allow for everything while the command printed that it blocked.
HOOK_EXT = "__HOOK_EXT__"
# Candidate argv prefixes, first whose binary exists wins. PowerShell is called `powershell` on
# Windows and `pwsh` everywhere else, so baking one name made the adapter crash on the other
# platform - and a crashing adapter is a guard that does not run.
HOOK_RUNNERS = __HOOK_RUNNERS__


def resolve_runner():
    for argv in HOOK_RUNNERS:
        if shutil.which(argv[0]):
            return argv
    return None

event = sys.argv[1] if len(sys.argv) > 1 else ""
try:
    payload = json.load(sys.stdin)
except Exception:
    print(json.dumps({"permission": "allow"})); sys.exit(0)

# The hook runs with cwd = the project root (that is how Cursor invokes this adapter), and the hook
# is addressed by a RELATIVE path from there. Passing bash an absolute drive-letter path (C:\...)
# fails to resolve on Windows bash and would make the guard silently allow everything.
cwd = payload.get("cwd") or "."

if event == "shell":
    claude = {"cwd": cwd, "tool_name": "Bash",
              "tool_input": {"command": payload.get("command", "")}}
    names = ["guard-main-commit", "check-commit-msg", "protect-secrets"]
elif event == "read":
    claude = {"cwd": cwd, "tool_name": "Read",
              "tool_input": {"file_path": payload.get("file_path", "")}}
    names = ["protect-adr", "protect-secrets"]
elif event == "edit":
    claude = {"cwd": cwd, "tool_name": "Edit",
              "tool_input": {"file_path": payload.get("file_path", "")}}
    names = ["protect-adr", "protect-secrets"]
else:
    print(json.dumps({"permission": "allow"})); sys.exit(0)

blob = json.dumps(claude)
runner = resolve_runner()
for name in names:
    rel = f".claude/hooks/{name}.{HOOK_EXT}"
    if not (pathlib.Path(cwd) / rel).is_file():
        continue
    if runner is None:
        # A guard that cannot execute must not answer "allow". It does not know. Denying is
        # loud and fixable (install the interpreter, or re-port with the other hook flavour);
        # allowing would be the silent hole this adapter exists to close.
        print(json.dumps({"permission": "deny", "user_message": (
            f"Cannot run {rel}: none of "
            f"{', '.join(a[0] for a in HOOK_RUNNERS)} is on PATH, so the guard could not be "
            f"evaluated. Install one, or re-run port.py against a harness whose hooks match "
            f"this machine.")}))
        sys.exit(0)
    r = subprocess.run([*runner, rel], input=blob, capture_output=True, text=True, cwd=cwd)
    if r.returncode == 2:  # the hook blocked
        print(json.dumps({"permission": "deny",
                          "user_message": (r.stderr.strip() or f"{name} blocked this action.")}))
        sys.exit(0)
print(json.dumps({"permission": "allow"}))
'''


def port_codex_hooks(claude_hooks: pathlib.Path, dest: pathlib.Path, ext: str,
                     force: bool = False) -> list[tuple[str, pathlib.Path]]:
    """Codex payload == Claude payload, so register the existing hooks directly. No adapter."""
    dest.mkdir(parents=True, exist_ok=True)
    # Codex registers a bare command string, so unlike the Cursor adapter there is nowhere to
    # resolve the interpreter at run time. Resolve it here instead: port.py runs on the machine
    # that will run the hooks, so preferring the name that actually exists is the correct
    # semantics even though it makes the output machine-dependent.
    if ext == "sh":
        runner = "bash"
    else:
        exe = "pwsh" if (shutil.which("pwsh") or not shutil.which("powershell")) else "powershell"
        runner = f"{exe} -NoProfile -ExecutionPolicy Bypass -File"

    def cmd(name: str) -> str:
        return f"{runner} .claude/hooks/{name}.{ext}"

    reg = {
        # Provenance, first key so it is the first thing a reader sees in the diff. Underscore
        # prefix because that is the conventional "not part of the schema" marker in a tool's
        # config, and Codex ignores keys it does not know rather than failing the file.
        "_generated_by": GENERATED_BY,
        "hooks": {
            "PreToolUse": [
                {"matcher": "Bash",
                 "hooks": [{"type": "command", "command": cmd(n),
                            "statusMessage": f"harness: {n}"} for n in BASH_HOOKS]},
                {"matcher": "apply_patch",
                 "hooks": [{"type": "command", "command": cmd("protect-secrets"),
                            "statusMessage": "harness: protect-secrets"}]},
            ]
        }
    }
    out = dest / "hooks.json"
    return [(emit(out, json.dumps(reg, indent=2) + "\n", force), out)]


def port_cursor_hooks(dest: pathlib.Path, ext: str,
                      force: bool = False) -> list[tuple[str, pathlib.Path]]:
    dest.mkdir(parents=True, exist_ok=True)
    adapter = dest / "cursor-adapter.py"
    runners = [["bash"]] if ext == "sh" else [
        [exe, "-NoProfile", "-ExecutionPolicy", "Bypass", "-File"]
        for exe in ("pwsh", "powershell")]
    body = (CURSOR_ADAPTER
            .replace("__HOOK_EXT__", ext)
            .replace("__HOOK_RUNNERS__", repr(runners)))
    reg = {
        # Same provenance key as the Codex registration, same reasoning. The adapter carries the
        # marker in its own header comment already.
        "_generated_by": GENERATED_BY,
        "version": 1,
        "hooks": {
            "beforeShellExecution": [{"command": f"python3 .cursor/hooks/{adapter.name} shell"}],
            "beforeReadFile": [{"command": f"python3 .cursor/hooks/{adapter.name} read"}],
            "afterFileEdit": [{"command": f"python3 .cursor/hooks/{adapter.name} edit"}],
        },
    }
    regfile = dest.parent / "hooks.json"
    return [(emit(regfile, json.dumps(reg, indent=2) + "\n", force), regfile),
            (emit(adapter, body, force), adapter)]


# --------------------------------------------------------------------------- self-test

def self_test() -> int:
    """Both flavors. Posix-only coverage is why a windows harness once produced a Cursor adapter
    that allowed everything while the command printed that it blocked."""
    rc = 0
    for flavor in ("posix", "windows"):
        rc |= self_test_flavor(flavor)
    return rc


def self_test_contract(repo: pathlib.Path, flavor: str) -> tuple[int, int]:
    """Assert the non-destructive contract end to end against a real ported repo.

    Every emitter here used to call write_text() unconditionally, so a second port silently
    replaced whatever a human had done to the .mdc rules or the hooks.json in between - and the
    report said the port had succeeded, because by its own account it had. These checks need no
    hook interpreter, so unlike the behaviour half below they run on every machine.

    Returns (passed, failed).
    """
    npass = nfail = 0
    quiet = io.StringIO()   # port() is chatty and this suite has its own one-line-per-check format

    def check(ok: bool, what: str) -> None:
        nonlocal npass, nfail
        print(f"  {'ok  ' if ok else 'FAIL'}  {flavor:5} {what}")
        npass += bool(ok)
        nfail += not ok

    first = port_all(repo, "all")
    check(bool(first) and all(s == "ADDED" for s, _ in first),
          f"first port reports ADDED for all {len(first)} files")

    # mtime as well as bytes: KEPT has to mean "not rewritten", not "rewritten with the same
    # content". Identical content is what a destructive rewrite of a clean tree looks like.
    before = {p: (p.stat().st_mtime_ns, p.read_bytes()) for _, p in first}
    second = port_all(repo, "all")
    untouched = all(p.stat().st_mtime_ns == before[p][0] and p.read_bytes() == before[p][1]
                    for _, p in second)
    check(all(s == "KEPT" for s, _ in second) and untouched,
          "re-port reports KEPT and rewrites nothing")

    unmarked = [p.name for _, p in second if GENERATED_BY not in p.read_text(encoding="utf-8")]
    check(not unmarked,
          f'every emitted file carries "{GENERATED_BY}"'
          + (f" (missing: {', '.join(unmarked)})" if unmarked else ""))

    # One of each emitted format, because they take different code paths to disk.
    mdc = next(p for _, p in second if p.suffix == ".mdc")
    js = next(p for _, p in second if p.name == "hooks.json")
    hand = b"# a human edited this after the port; clobbering it is the bug\n"
    for p in (mdc, js):
        p.write_bytes(hand)

    third = {p: s for s, p in port_all(repo, "all")}
    check(third[mdc] == "CONFLICT" and third[js] == "CONFLICT",
          "a hand-edited .mdc and hooks.json report CONFLICT")
    check(mdc.read_bytes() == hand and js.read_bytes() == hand,
          "a CONFLICT file is left byte-identical to the hand edit")

    with contextlib.redirect_stdout(quiet):
        rc = port(repo, "all")
    check(rc != 0, f"port() exits non-zero while a CONFLICT stands -> {rc} (want non-zero)")

    forced = {p: s for s, p in port_all(repo, "all", force=True)}
    check(forced[mdc] == "FORCED" and forced[js] == "FORCED"
          and mdc.read_bytes() != hand and js.read_bytes() != hand,
          "--force reports FORCED and overwrites the hand edit")
    return npass, nfail


def self_test_flavor(flavor: str) -> int:
    """Run the Cursor adapter logic against the documented sample payloads, in a temp harness, so
    the translation is exercised rather than trusted. Needs a runner and a scaffolded harness on
    disk; if neither is present, this reports SKIP rather than a false pass."""
    ext = "sh" if flavor == "posix" else "ps1"
    here = pathlib.Path(__file__).resolve().parent
    scaffold = here / "scaffold.py"
    if not scaffold.is_file():
        print("  SKIP: scaffold.py not found next to port.py"); return 0

    # Scaffold into a workdir next to this script, not the system temp dir: on Windows the bash that
    # runs the hooks may not share a filesystem view with a Python temp dir, which would make the
    # hooks look broken when they are fine.
    wd = here.parent / f".port-selftest-{flavor}"
    def _force(fn, path, _e):
        import os as _os
        _os.chmod(path, 0o700); fn(path)
    if wd.exists():
        shutil.rmtree(wd, onexc=_force)
    wd.mkdir(parents=True)
    try:
        repo = wd / "repo"
        vars_json = wd / "vars.json"
        payload = json.loads(json.dumps(_TEST_VARS))   # deep copy per flavor
        payload["flags"] = [f for f in payload["flags"] if f not in ("posix", "windows")] + [flavor]
        payload["vars"]["HOOK_RUNNER"] = (
            "bash" if ext == "sh" else "powershell -NoProfile -ExecutionPolicy Bypass -File")
        payload["vars"]["HOOK_EXT"] = ext
        vars_json.write_text(json.dumps(payload), encoding="utf-8")
        r = subprocess.run([sys.executable, str(scaffold), "--target", str(repo),
                            "--vars", str(vars_json)], capture_output=True, text=True)
        if r.returncode != 0:
            print("  SKIP: could not scaffold a test harness:\n" + r.stdout[-400:]); return 0
        adr = repo / "docs/architecture/decisions"
        adr.mkdir(parents=True, exist_ok=True)
        (adr / "ADR-001.md").write_text("---\nstatus: Accepted\n---\n", encoding="utf-8")
        for c in (["git", "init", "-q", "-b", "main"], ["git", "config", "user.email", "e@e"],
                  ["git", "config", "user.name", "n"], ["git", "add", "-A"],
                  ["git", "commit", "-qm", "init"]):
            subprocess.run(c, cwd=str(repo), capture_output=True)

        # The write contract first: it needs no interpreter, so it is the half of this suite that
        # runs everywhere. It also leaves a fully ported repo behind for the checks below.
        npass, nfail = self_test_contract(repo, flavor)

        port_cursor_hooks(repo / ".cursor" / "hooks", ext)
        adapter = (repo / ".cursor/hooks/cursor-adapter.py").resolve()
        rcwd = repo.resolve().as_posix()

        # Static wiring check first. This is the one that matters: a windows harness with an
        # adapter pointing at .sh finds no hook, skips every one, and returns allow for
        # everything while the command prints that it blocks. That shipped once.
        body = adapter.read_text(encoding="utf-8")
        wired = f'HOOK_EXT = "{ext}"' in body
        print(f"  {'ok  ' if wired else 'FAIL'}  {flavor:5} adapter targets .{ext} hooks")
        npass += int(wired)
        nfail += int(not wired)

        # PowerShell is `powershell` on Windows and `pwsh` everywhere else. Baking one name
        # made the adapter crash on the other platform, and a crashed adapter is a guard that
        # never ran. This machine has whatever it has, so assert the list, not the lookup.
        want_names = ["bash"] if ext == "sh" else ["pwsh", "powershell"]
        named = all(f"'{n}'" in body for n in want_names)
        print(f"  {'ok  ' if named else 'FAIL'}  {flavor:5} adapter offers every interpreter"
              f" name ({', '.join(want_names)})")
        npass += named
        nfail += not named

        # A guard that cannot execute must deny, never allow. Only reachable by removing every
        # candidate, which no real machine does, so it is forced here.
        broken = adapter.parent / "adapter-no-runner.py"
        broken.write_text(re.sub(r"^HOOK_RUNNERS = .+$", "HOOK_RUNNERS = [['no-such-binary']]",
                                 body, count=1, flags=re.M), encoding="utf-8")
        r = subprocess.run([sys.executable, str(broken), "shell"],
                           input=json.dumps({"command": "npm test", "cwd": rcwd}),
                           capture_output=True, text=True, cwd=str(repo))
        try:
            got = json.loads(r.stdout).get("permission")
        except Exception:
            got = f"BAD OUTPUT: {r.stdout!r} {r.stderr[:120]!r}"
        # npm test is an ALLOW case when the guard runs, so `deny` here can only come from the
        # missing interpreter - which is exactly the fail-closed path being asserted.
        closed = got == "deny"
        print(f"  {'ok  ' if closed else 'FAIL'}  {flavor:5} adapter fails closed when no"
              f" interpreter exists -> {got} (want deny)")
        npass += closed
        nfail += not closed

        runner = "bash" if ext == "sh" else (shutil.which("pwsh") or shutil.which("powershell"))
        if ext == "sh" and not shutil.which("bash"):
            runner = None
        if runner is None:
            print(f"  SKIP: no runner for .{ext} hooks; wiring checked, behaviour not exercised")
            return 1 if nfail else 0

        cases = [
            ("shell", {"command": "cat .env", "cwd": rcwd}, "deny"),
            ("shell", {"command": "git commit -m 'x'", "cwd": rcwd}, "deny"),   # on main
            ("shell", {"command": "npm test", "cwd": rcwd}, "allow"),
            ("read",  {"file_path": f"{rcwd}/.env", "cwd": rcwd}, "deny"),
            ("read",  {"file_path": f"{rcwd}/src/x.ts", "cwd": rcwd}, "allow"),
            ("edit",  {"file_path": f"{rcwd}/docs/architecture/decisions/ADR-001.md",
                       "cwd": rcwd}, "deny"),
        ]
        for event, payload, want in cases:
            r = subprocess.run([sys.executable, str(adapter), event],
                               input=json.dumps(payload), capture_output=True, text=True,
                               cwd=str(repo))
            try:
                got = json.loads(r.stdout).get("permission")
            except Exception:
                got = f"BAD OUTPUT: {r.stdout!r} {r.stderr[:120]!r}"
            ok = got == want
            label = payload.get("command") or payload.get("file_path", "").split("/")[-1]
            print(f"  {'ok  ' if ok else 'FAIL'}  {flavor:5} {event:5} {label:<34} -> {got} (want {want})")
            npass += ok
            nfail += not ok
        print(f"  {npass}/{npass + nfail} {flavor} adapter checks pass.")
        # The deck and the outline quote this total, and it sat at "5/5" for several releases
        # after the suite grew. scripts/check_numbers.py reads the constant; this asserts it.
        if npass + nfail != CHECKS_PER_FLAVOR:
            print(f"  FIGURE DRIFT: ran {npass + nfail} checks, but CHECKS_PER_FLAVOR says "
                  f"{CHECKS_PER_FLAVOR}. Update it at the top of this file and re-run "
                  f"scripts/check_numbers.py to refresh the published figures.", file=sys.stderr)
            nfail += 1
        return 1 if nfail else 0
    finally:
        shutil.rmtree(wd, onexc=_force)


_TEST_VARS = {
    "vars": {k: "x" for k in [
        "PROJECT_NAME", "PROJECT_SLUG", "DEFAULT_BRANCH", "PR_OR_MR", "CI_PLATFORM", "HOSTING",
        "GIT_PLATFORM", "PR_CLI", "CI_STATUS_CMD",
        "UNIT_FRAMEWORK", "E2E_FRAMEWORK", "COVERAGE_TARGET", "TEST_CMD", "LINT_CMD", "BUILD_CMD",
        "DB_RESET_CMD", "DEPLOY_CMD", "ORM", "COMMIT_SCOPES", "SOURCE_GLOBS", "UI_GLOBS", "DB_GLOBS",
        "TEST_GLOBS", "PII_OR_DATA", "ROUTING_TABLE", "AGENT_ROSTER_TABLE", "DEV_AGENT_NAME",
        "DOMAIN", "DOMAIN_DESCRIPTION", "MODULE_PATHS", "FR_LIST", "COMMIT_TYPES", "DB_RESET_PATTERN",
        "MODEL_PUBLIC", "MODEL_INTERNAL", "MODEL_CONFIDENTIAL", "MODEL_RESTRICTED", "DATA_RESIDENCY",
        "ALLOWED_LICENCES", "DENIED_LICENCES", "IP_OWNERSHIP_STATEMENT", "DEP_MANIFEST_GLOBS",
        "GATED_ACTIONS", "INCIDENT_CONTACT", "DOC_LANGUAGE",
    ]},
    "flags": ["posix", "ui", "db", "ai", "tests", "unit", "e2e"],
}
_TEST_VARS["vars"]["HISTORY_LEVEL"] = "summary"
_TEST_VARS["vars"]["HISTORY_KEEP"] = "200"
_TEST_VARS["vars"]["DEFAULT_BRANCH"] = "main"
_TEST_VARS["vars"]["HOOK_RUNNER"] = "bash"
_TEST_VARS["vars"]["HOOK_EXT"] = "sh"
_TEST_VARS["vars"]["SOURCE_GLOBS"] = '"src/**/*.ts"'
_TEST_VARS["vars"]["RESTRICTED_DENIES"] = '"Read(**/.restricted/**)",'
_TEST_VARS["vars"]["GLOSSARY_SEED"] = "| - | seeded at bootstrap | - | - |"


def port_all(target: pathlib.Path, tool: str,
             force: bool = False) -> list[tuple[str, pathlib.Path]]:
    """Emit every file `tool` needs and return [(status, path)], printing nothing.

    Split out of port() so the self-test can assert on the statuses themselves rather than on
    scraped stdout - a contract asserted through printed text is a contract that silently stops
    being asserted the day someone rewords the report.
    """
    claude = target / ".claude"
    rules = claude / "rules"
    hooks = claude / "hooks"
    if not rules.is_dir():
        raise SystemExit(f"no {rules} - scaffold the Claude harness first (run harness-bootstrap).")
    ext = "sh" if (hooks / "protect-secrets.sh").is_file() else "ps1"

    results: list[tuple[str, pathlib.Path]] = []
    if tool in ("cursor", "all"):
        results += port_cursor_rules(rules, target / ".cursor" / "rules", force)
        results += port_cursor_hooks(target / ".cursor" / "hooks", ext, force)
    if tool in ("codex", "all"):
        results += port_codex_hooks(hooks, target / ".codex", ext, force)
    return results


def port(target: pathlib.Path, tool: str, force: bool = False) -> int:
    """Port, report, and return the exit code: non-zero if anything is in CONFLICT."""
    results = port_all(target, tool, force)
    rel = {p: p.relative_to(target).as_posix() for _, p in results}

    if tool in ("cursor", "all"):
        nrules = sum(1 for _, p in results if p.suffix == ".mdc")
        adapter = next(rel[p] for _, p in results if p.name == "cursor-adapter.py")
        print(f"\nCursor:")
        print(f"  .cursor/rules/      {nrules} rules (.md -> .mdc, paths: -> globs:)")
        print(f"  .cursor/hooks.json  registers the beforeShellExecution / beforeReadFile adapter")
        print(f"  {adapter}  the adapter (Cursor payload -> harness hooks)")
        print(f"  note: Cursor's afterFileEdit is observational, so an edit to an Accepted ADR is")
        print(f"        flagged after the fact, not blocked before. Everything else blocks pre-hoc.")
        print(f"  note: guard-agent-spawn does not port - Cursor has no subagent-spawn hook point,")
        print(f"        so the spawn boundary is rules text there, not an enforced gate.")

    if tool in ("codex", "all"):
        h = next(rel[p] for _, p in results if p.parts[-2:] == (".codex", "hooks.json"))
        print(f"\nCodex:")
        print(f"  AGENTS.md           already generated by harness-bootstrap - Codex reads it natively")
        print(f"  {h}   registers the existing hooks (Codex payload == Claude payload)")
        print(f"  note: Codex routes file edits through apply_patch (path inside tool_input.command),")
        print(f"        so protect-adr is best-effort there; the Bash-based guards are exact.")
        print(f"  note: guard-agent-spawn does not port - Codex has no Agent tool, so the spawn")
        print(f"        boundary is rules text there, not an enforced gate.")

    # Same report shape as the scaffolder's, deliberately: one person runs both, and two different
    # vocabularies for the same four outcomes is how a KEPT gets read as a write.
    by = {k: sorted(rel[p] for s, p in results if s == k)
          for k in ("ADDED", "KEPT", "CONFLICT", "FORCED")}

    def show(label: str, items: list[str]) -> None:
        if not items:
            return
        print(f"\n{label} ({len(items)}):")
        for i in items:
            print(f"  {i}")

    show("ADDED", by["ADDED"])
    show("KEPT (already identical)", by["KEPT"])
    show("CONFLICT (exists and differs - not written)", by["CONFLICT"])
    show("OVERWRITTEN (--force)", by["FORCED"])
    print(f"\nSummary: {len(by['ADDED']) + len(by['FORCED'])} written, {len(by['KEPT'])} kept, "
          f"{len(by['CONFLICT'])} conflict"
          + (f", {len(by['FORCED'])} overwritten (--force)." if by["FORCED"] else "."))

    if by["CONFLICT"]:
        # Unlike the scaffolder, this IS an error. The scaffolder's conflicts are the expected
        # brownfield queue; a porter's conflicts mean the ported harness on disk is now part this
        # run and part something else, and a half-applied port that exits 0 is exactly the failure
        # this contract was added to stop - CI would go green over it.
        print("\nCONFLICT means the file differs from what this port would write and was LEFT ALONE.\n"
              "Reconcile it by hand, or re-run with --force for the files you have decided to\n"
              "replace. Exiting non-zero: a partially applied port must not read as a clean one.")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Port a scaffolded harness to Cursor or Codex.")
    ap.add_argument("--target", type=pathlib.Path, help="repo that already has a scaffolded .claude/")
    ap.add_argument("--tool", choices=["cursor", "codex", "all"], default="all")
    ap.add_argument("--force", action="store_true",
                    help="overwrite files that exist and differ (reported as FORCED)")
    ap.add_argument("--self-test", action="store_true", help="test the adapter on sample payloads")
    a = ap.parse_args()

    if a.self_test:
        print("Cursor adapter self-test:")
        return self_test()
    if not a.target:
        ap.error("--target is required unless --self-test")
    return port(a.target.resolve(), a.tool, a.force)


if __name__ == "__main__":
    sys.exit(main())
