#!/usr/bin/env python3
"""Build the GitHub wiki from this repository, so it cannot drift from it.

A wiki is the easiest documentation in a project to let rot: it lives in a
separate git repo nobody clones, so nothing in CI ever reads it, and the counts
inside it go stale silently. Every reference page here is therefore GENERATED
from the assets themselves - the roster from the agent frontmatter, the hooks
from their registration file, the flags from the scaffolder's own KNOWN_FLAGS.
If an asset changes, the page changes with it or this script fails.

The narrative pages (Home, Getting Started, and so on) are hand-written and live
in docs/wiki/. They are copied through unchanged.

    python scripts/build_wiki.py                 # build into dist/wiki/
    python scripts/build_wiki.py --check         # build and diff against docs/wiki, exit 1 on drift
    python scripts/build_wiki.py --out DIR       # build somewhere else

Publishing is a separate, deliberate step: see docs/wiki/README-publishing.md.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "harness-bootstrap/assets/claude"
NARRATIVE = ROOT / "docs/wiki"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/build_wiki.py from the repository assets. -->\n"
    "<!-- Do not edit this page in the wiki UI: the next build overwrites it. -->\n\n"
)


# --------------------------------------------------------------------------- helpers
def frontmatter(path: pathlib.Path) -> dict[str, str]:
    """Parse the leading --- block. Values are kept as raw strings, because the
    templates contain {{VARS}} and conditional markers that are not valid YAML."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if line.startswith("#") or ":" not in line:
            continue
        k, _, v = line.partition(":")
        out[k.strip()] = v.strip()
    return out


def manifest_entries() -> list[dict]:
    m = json.loads((ROOT / "harness-bootstrap/assets/manifest.json").read_text(encoding="utf-8"))
    return m if isinstance(m, list) else m.get("files", m.get("items", []))


# `windows` and `posix` select the hook FLAVOUR, not whether a control exists. Every
# hook ships in both, and the manifest carries one entry per flavour with the same
# stem. Reporting "needs windows" for all ten of them - which the first build did -
# says something false about every guardrail in the project.
OS_FLAGS = {"windows", "posix"}


def gating_for(dest_stem: str, kind: str, entries: list[dict]) -> str:
    """-> a human phrase for when this asset is installed.

    All entries sharing the stem are considered, because an asset shipped in two
    flavours has two manifest rows and reading only the first picks one arbitrarily.
    """
    need: set[str] = set()
    any_: set[str] = set()
    not_: set[str] = set()
    found = False
    for e in entries:
        dest = str(e.get("dest", ""))
        if f"{kind}/" in dest and pathlib.Path(dest).stem == dest_stem:
            found = True
            need |= set(e.get("when") or []) - OS_FLAGS
            any_ |= set(e.get("when_any") or []) - OS_FLAGS
            not_ |= set(e.get("when_not") or []) - OS_FLAGS
    if not found:
        return "always"
    bits = []
    if need:
        bits.append("needs " + " and ".join(f"`{f}`" for f in sorted(need)))
    if any_:
        bits.append("needs " + " or ".join(f"`{f}`" for f in sorted(any_)))
    if not_:
        bits.append("absent when " + " or ".join(f"`{f}`" for f in sorted(not_)))
    return "; ".join(bits) if bits else "always"


def detemplate(s: str) -> str:
    """Turn an asset's template text into something a reader can parse.

    Asset frontmatter is a template: it carries {{VARS}} the scaffolder fills in and
    {{#IF_FLAG}} blocks it resolves. Copied raw into a wiki page those read as noise,
    and the conditional markers contain characters that break a markdown table.
    """
    words = {
        "PR_OR_MR": "pull request", "DEFAULT_BRANCH": "the default branch",
        "PROJECT_NAME": "the project", "ORM": "the ORM", "CI_PLATFORM": "CI",
        "HOSTING": "the hosting target", "UNIT_FRAMEWORK": "the unit framework",
        "E2E_FRAMEWORK": "the e2e framework",
    }
    s = re.sub(r"\{\{[#^/]IF_[A-Z0-9_]+\}\}", "", s)      # conditional markers
    s = re.sub(r"\{\{([A-Z0-9_]+)\}\}",
               lambda m: words.get(m.group(1), m.group(1).lower().replace("_", " ")), s)
    return re.sub(r"\s+", " ", s).strip()


def first_sentence(s: str, limit: int = 200) -> str:
    s = detemplate(s)
    m = re.search(r"(.+?[.!?])(\s|$)", s)
    out = m.group(1) if m else s
    return out if len(out) <= limit else out[: limit - 1].rstrip() + "…"


def cell(s: str) -> str:
    """A markdown table cell. The pipe is the column separator, so a literal one in
    the content silently splits the row into extra columns - which is exactly what
    a hook matcher like `Edit|Write` did on the first build of this page."""
    return s.replace("|", "\\|")


def table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(cell(c) for c in r) + " |" for r in rows]
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------- pages
def page_agents(entries: list[dict]) -> str:
    rows = []
    for p in sorted((ASSETS / "agents").glob("*.md")):
        fm = frontmatter(p)
        if p.stem == "dev-agent":
            continue
        rows.append([
            f"`{p.stem}`",
            fm.get("model", "?"),
            fm.get("effort", "?"),
            fm.get("maxTurns", "-"),
            gating_for(p.stem, "agents", entries),
            first_sentence(fm.get("description", ""), 150),
        ])
    body = GENERATED_BANNER + f"""# Agent reference

The seats this harness can install. **A run installs between {roster_lo} and {roster_hi} of them**,
decided by the contract and by what the codebase analysis found, plus one `dev-agent` per module
that actually exists. Never all of them by default: see [[Tailored Build]].

Every seat carries an explicit `model` and `effort`. An unset model means `inherit`, which silently
bills mechanical work at the caller's tier, so the harness never leaves it unset.

{table(["Seat", "Model", "Effort", "maxTurns", "Installed", "What it is for"], rows)}
### Reviewers hold no write tools

`code-reviewer` and `security-reviewer` (or the merged `reviewer` under the `solo_review` flag) have
no `Edit` and no `Write`. Not "usually" - none. A reviewer that can edit is not a review gate.

### The template seat

`dev-agent.md` is not in the table because it is a template, instantiated once per module with that
module's real paths as its scope. A module with no seat, or a seat with no module, is a finding in
`harness-view assess`.
"""
    return body


def page_rules(entries: list[dict]) -> str:
    rows = []
    for p in sorted((ASSETS / "rules").glob("*.md")):
        fm = frontmatter(p)
        text = p.read_text(encoding="utf-8")
        scoped = "paths:" in text.split("---")[1] if text.startswith("---") else False
        # Search for the heading in the BODY only. Frontmatter carries YAML comments
        # that start with '#', and reading the first one as the title pulled a raw
        # {{SOURCE_GLOBS}} template line into the page.
        body = text
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                body = text[end + 4:]
        heading = ""
        m = re.search(r"^#\s+(.+)$", body, re.M)
        if m:
            heading = detemplate(m.group(1))
        rows.append([
            f"`{p.stem}`",
            "path-scoped" if scoped else "**every session**",
            gating_for(p.stem, "rules", entries),
            heading,
        ])
    return GENERATED_BANNER + f"""# Rule reference

Rules are markdown files the agent reads. The ones marked **every session** are a permanent context
cost on every request; the path-scoped ones enter the window only when a matching file is touched.

That distinction is the whole context budget: **{tax_pct}% of rule content stays out of the default
session** because {scoped_rules} of the {total_rules} rules are path-scoped.

{table(["Rule", "Loading", "Installed", "Covers"], rows)}
### Why this matters more than it looks

A rule that matches no file in your repository is not free. It is a tax on every request, forever.
`harness-view assess` reports a rule with no matching path as a finding for exactly that reason.
"""


def page_hooks(entries: list[dict]) -> str:
    reg = json.loads((ASSETS / "hooks/registration.posix.json").read_text(encoding="utf-8"))
    by_hook: dict[str, list[tuple[str, str]]] = {}
    for event, groups in reg.get("hooks", {}).items():
        for g in groups:
            matcher = g.get("matcher", "*")
            for h in g.get("hooks", []):
                m = re.search(r"([\w-]+)\.sh", h.get("command", ""))
                if m:
                    by_hook.setdefault(m.group(1), []).append((event, matcher))

    stems = sorted({p.stem for p in (ASSETS / "hooks").glob("*.*")
                    if p.suffix in (".sh", ".ps1")})
    rows = []
    for stem in stems:
        wiring = by_hook.get(stem, [])
        gate = gating_for(stem, "hooks", entries)
        if wiring:
            events = ", ".join(sorted({e for e, _ in wiring}))
            matchers = ", ".join(sorted({f"`{m}`" for _, m in wiring}))
        else:
            # An opt-in hook is registered by the scaffolder only when its flag is set,
            # so it is absent from the base registration file. Saying "not registered"
            # would read as a defect; the manifest knows the real answer.
            events = "opt-in" if gate != "always" else "not registered"
            matchers = "-"
        rows.append([f"`{stem}`", events, matchers, gate])

    return GENERATED_BANNER + f"""# Hook reference

Hooks are the gate. A hook reads the tool call as JSON on stdin and decides with an exit code:

| Exit | Meaning |
|---|---|
| `0` | allow the call |
| `2` | **block it**, and the message on stderr is shown to the agent |

This is why the safety floor does not depend on the model. A rule can be ignored by a model that
decides not to follow it. An exit code cannot.

Both flavours ship: `.sh` for macOS and Linux, `.ps1` for Windows. The flavour and the
`settings.json` registration are derived from one flag, so a mismatch is unrepresentable - a
harness whose hooks are registered for the wrong flavour finds no hook, blocks nothing, and reports
that it blocked. That shipped once.

{table(["Hook", "Event", "Matches tools", "Installed"], rows)}
### Proving they fire

`python eval/guardrail_eval.py` scaffolds a real harness and fires {eval_cases} payloads at it per
hook flavour, {eval_block} that must be blocked and {eval_allow} that must be allowed. Swap every
agent from Opus to Haiku and the result is byte-identical.
"""


def page_commands(entries: list[dict]) -> str:
    rows = []
    for p in sorted((ASSETS / "commands").glob("*.md")):
        fm = frontmatter(p)
        rows.append([
            f"`/{p.stem}`",
            gating_for(p.stem, "commands", entries),
            first_sentence(fm.get("description", ""), 160),
        ])
    return GENERATED_BANNER + f"""# Command reference

Slash commands installed into `.claude/commands/`. Each is a markdown file: read it, change it, or
delete it.

{table(["Command", "Installed", "What it does"], rows)}
### Turning things off

`/harness-toggle` moves a rule, command or hook into `.claude/disabled/` and records the change in
the committed `.claude/disabled.json`, including the hook's `settings.json` registration verbatim so
enabling restores it byte-exactly. A re-run of the scaffolder respects it, so a toggled-off control
is never silently resurrected.

Safety-critical controls need a typed confirmation phrase rather than a yes. Agents cannot toggle
anything at all.
"""


def page_flags() -> str:
    src = (ROOT / "harness-bootstrap/scripts/scaffold.py").read_text(encoding="utf-8")
    m = re.search(r"KNOWN_FLAGS = \{(.*?)\}", src, re.S)
    flags = sorted(re.findall(r'"([a-z_]+)"', m.group(1))) if m else []

    meaning = {
        "ui": "the project has a frontend; installs the frontend rule and UI-aware guidance",
        "db": "the project has a database; installs the data-model rule and the data-modeler seat",
        "db_engineer": "split out a dedicated database engineer seat",
        "db_seeder": "split out a dedicated seeding seat and the seed command",
        "ai": "the project calls a model at run time; installs the AI-governance surface",
        "audit": "read-only mode: agents analyse but never modify the source",
        "tdd": "test-first delivery; tests are written before the implementation",
        "ddd": "domain-driven delivery; shared language and bounded contexts",
        "light": "minimal ceremony; no methodology rule, review gate kept",
        "unit": "agents automate unit tests",
        "e2e": "agents automate end-to-end tests",
        "tests": "derived: set when either `unit` or `e2e` is chosen",
        "deploy_ask": "deployment is gated behind an explicit human confirmation",
        "long": "long-lived project; adds the Tier 3 seats (brainstormer, tech-researcher, history-tracker)",
        "solo_review": "one merged reviewer seat instead of separate code and security reviewers",
        "windows": "ship `.ps1` hooks and register them for PowerShell",
        "posix": "ship `.sh` hooks and register them for bash",
        "terse": "install the terse output-style rule",
        "rtk": "install the opt-in rtk wrapper hook",
        "pr_cli": "a pull-request CLI is available, so commands may call it",
    }
    rows = [[f"`{f}`", meaning.get(f, "")] for f in flags]
    return GENERATED_BANNER + f"""# Flag reference

Flags are how the questionnaire's answers reach the scaffolder. They gate whole assets and
conditional blocks inside them, which is what makes the build tailored rather than comprehensive.

Exactly one of `windows` / `posix` is required. The scaffolder validates the set and exits non-zero
on an unknown flag, so a typo fails loudly instead of silently dropping a section.

{table(["Flag", "What it turns on"], rows)}
### Seeing the effect

Scaffold with the leanest answers and you get {roster_lo} seats. Answer yes to databases, tests and
a long-lived project and you get {roster_hi}. The range is computed from the scaffolder's own
selection logic, so it cannot drift: see `scripts/check_numbers.py`.
"""


# --------------------------------------------------------------------------- validate
CELL_SPLIT = re.compile(r"(?<!\\)\|")
ROW_SEP = re.compile(r"\|(?:\s*-{3,}\s*\|)+")


def validate(out: pathlib.Path) -> list[str]:
    """Check the built pages before anyone pushes them to a wiki nothing else reads.

    Each rule here caught a real defect on the first build: a hook matcher containing
    `Edit|Write` split its row into extra columns, and a YAML comment in a rule's
    frontmatter was read as the page title, carrying a raw {{SOURCE_GLOBS}} into it.
    """
    problems: list[str] = []
    pages = sorted(out.glob("*.md"))
    names = {p.stem for p in pages}

    def cells(line: str) -> int:
        return len(CELL_SPLIT.split(line.strip())) - 2

    for p in pages:
        text = p.read_text(encoding="utf-8")
        lines = text.splitlines()

        i = 0
        while i < len(lines):
            if (lines[i].startswith("|") and i + 1 < len(lines)
                    and ROW_SEP.fullmatch(lines[i + 1].strip())):
                want = cells(lines[i])
                j = i + 2
                while j < len(lines) and lines[j].startswith("|"):
                    if cells(lines[j]) != want:
                        problems.append(
                            f"BAD TABLE {p.name}:{j + 1} has {cells(lines[j])} cells, "
                            f"header has {want}")
                    j += 1
                i = j
            else:
                i += 1

        for m in re.finditer(r"\[\[([^\]]+)\]\]", text):
            target = m.group(1).replace(" ", "-")
            if target not in names:
                problems.append(f"DEAD LINK {p.name}: [[{m.group(1)}]] -> {target}.md missing")

        # A marker inside a code span is prose about templates, not a leak.
        for m in re.finditer(r"\{\{[^}]+\}\}", re.sub(r"`[^`\n]*`", "", text)):
            problems.append(f"TEMPLATE MARKER left in {p.name}: {m.group(0)}")

        if "—" in text:
            problems.append(f"EM-DASH in {p.name}")

    return problems


# --------------------------------------------------------------------------- build
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", default=str(ROOT / "dist/wiki"))
    ap.add_argument("--check", action="store_true",
                    help="fail if the narrative sources are missing rather than building silently")
    args = ap.parse_args()

    if not NARRATIVE.is_dir():
        print(f"missing {NARRATIVE.relative_to(ROOT)} - the narrative pages live there")
        return 1

    out = pathlib.Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    entries = manifest_entries()
    pages = {
        "Agent-Reference.md": page_agents(entries),
        "Rule-Reference.md": page_rules(entries),
        "Hook-Reference.md": page_hooks(entries),
        "Command-Reference.md": page_commands(entries),
        "Flag-Reference.md": page_flags(),
    }
    for name, body in pages.items():
        (out / name).write_text(body, encoding="utf-8", newline="")

    copied = 0
    for p in sorted(NARRATIVE.glob("*.md")):
        if p.name.startswith("README-"):
            continue          # publishing notes stay in the repo, not the wiki
        shutil.copyfile(p, out / p.name)
        copied += 1

    print(f"  generated {len(pages)} reference page(s) from the assets")
    print(f"  copied    {copied} narrative page(s) from docs/wiki/")
    print(f"  -> {out}")

    missing = [n for n in ("Home.md", "_Sidebar.md") if not (out / n).is_file()]
    if missing:
        print(f"  FAIL: the wiki needs {', '.join(missing)}")
        return 1

    problems = validate(out)
    for p in problems:
        print(f"  {p}")
    if problems:
        print(f"\n  {len(problems)} problem(s) in the built wiki.")
        return 1
    print("  pages validate: tables well formed, no dead links, no template markers")
    return 0


# Figures pulled in once, so every page quotes the same numbers as the rest of the repo.
sys.path.insert(0, str(ROOT / "scripts"))
from check_numbers import canonical, roster_range  # noqa: E402

_c = canonical()
roster_lo, roster_hi = roster_range()
tax_pct = _c["tax_pct"]
scoped_rules = _c["scoped_rules"]
total_rules = _c["rules"]
eval_cases = _c["eval_cases"]
eval_block = _c["eval_block"]
eval_allow = _c["eval_allow"]


if __name__ == "__main__":
    sys.exit(main())
